os: linux
language: c
compiler: gcc
before_install:
  - wget https://download.gnome.org/sources/vala/0.39/vala-0.39.5.tar.xz
  - tar xJvf vala-0.39.5.tar.xz
  - cd vala-0.39.5
  - ./configure --prefix=/usr
  - make -j12
  - sudo make install
  - cd ..
script:
  - make

